### ISSUE TITLE
OAT++ Swagger Resources are build into dev package

### ISSUE THREAD

**Issue by kmeinhar** [oatpp/meta-oatpp#2]
When creating Swagger component (e.g. [this example](https://github.com/oatpp/example-crud/blob/master/src/SwaggerComponent.hpp)) one has to provide a swagger resource path.
This path is supposed to contains files like:
* favicon-16x16.png
* index.html
* swagger-ui-bundle.js

Those file are currently build into the oatpp-swagger-dev package. Even tough the files are required at runtime and not at development time.
![image](https://user-images.githubusercontent.com/56924345/135811295-8b38df09-fa1b-4d9e-bcd5-678bb367d2fb.png)

**Comment by bamkrs** [comment]
Yes, this is an actual issue with the swagger-module having inappropriate installation path for the resources.
This was kind of addressed in an PR for the upcoming 1.3.0 release: https://github.com/oatpp/oatpp-swagger/pull/45 (Which originates from the creation of an meta-layer).
This is the reason why the meta-layer still flies as repository in my namespace, rather than in the official one. There are some things that still need to be addressed. 

> Those file are currently build into the oatpp-swagger-dev package. Even tough the files are required at runtime and not at development time.

Your definition of runtime and development time lack a bit of framing in this case. Theoretically its the other way around. In an production environment, you may do not want to have a swagger-ui hosted on your machine. However, while you are in a development/testing environment, you want to. Thus you want to have your swagger-ui in the development-package and the SDK, but not in the actual production image-package. 

Idealistically the oatpp-swagger recipe would not install the UI at all and the UI would be an recipe on its own. 
The base work for this is already done in https://github.com/bamkrs/meta-oatpp/blob/a6ca2c73743f07856cb72ad6b3b44baa0627ad26/recipes-oatpp/oatpp-swagger/oatpp-swagger_1.2.5.bb#L28
 However, this does not work because the expression is malformed due to bash trying to parse `${PN}` itself instead of just printing it: https://github.com/bamkrs/meta-oatpp/blob/a6ca2c73743f07856cb72ad6b3b44baa0627ad26/scripts/mkmodulerecipes#L62

**Comment by kmeinhar** [comment]
Resolved with commit 999703be68b80ae6d3ffdcffae116c2a58535fcd
